import type { GuidelineRule } from "./contracts.ts";

export const GUIDELINE_RULES: readonly GuidelineRule[] = [
  {
    schemaVersion: 1,
    ruleId: "WHO_FREE_SUGARS_LT_10_PERCENT_ENERGY",
    sourceId: "WHO_HEALTHY_DIET_2026",
    sourceSection: "Sugars; WHO sugars intake guideline 2015",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "ADULTS_AND_CHILDREN_WITHIN_SOURCE_SCOPE",
    metric: "free_sugars_percent_energy",
    operator: "LT",
    threshold: 10,
    unit: "percent_energy",
    ruleRole: "BENCHMARK",
    notes: [
      "WHO also suggests below 5% for additional health benefits; MoveFuel must not silently convert that suggestion into a universal hard target.",
    ],
  },
  {
    schemaVersion: 1,
    ruleId: "WHO_SATURATED_FAT_MAX_10_PERCENT_ENERGY",
    sourceId: "WHO_HEALTHY_DIET_2026",
    sourceSection: "Fats; WHO saturated/trans-fat guideline 2023",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "AGE_2_PLUS_WITHIN_SOURCE_SCOPE",
    metric: "saturated_fat_percent_energy",
    operator: "LTE",
    threshold: 10,
    unit: "percent_energy",
    ruleRole: "BENCHMARK",
    notes: ["Replacement nutrient quality matters; this benchmark does not prescribe a meal plan."],
  },
  {
    schemaVersion: 1,
    ruleId: "WHO_TRANS_FAT_MAX_1_PERCENT_ENERGY",
    sourceId: "WHO_HEALTHY_DIET_2026",
    sourceSection: "Fats; WHO saturated/trans-fat guideline 2023",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "AGE_2_PLUS_WITHIN_SOURCE_SCOPE",
    metric: "trans_fat_percent_energy",
    operator: "LTE",
    threshold: 1,
    unit: "percent_energy",
    ruleRole: "BENCHMARK",
    notes: ["Industrially produced trans fat should be avoided; the numeric benchmark does not imply a safe target to seek."],
  },
  {
    schemaVersion: 1,
    ruleId: "WHO_SODIUM_ADULT_LT_2000_MG_DAY",
    sourceId: "WHO_HEALTHY_DIET_2026",
    sourceSection: "Sodium; WHO sodium intake guideline 2012",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "ADULT_GENERAL_POPULATION_WITH_SOURCE_EXCEPTIONS",
    metric: "sodium_mg_day",
    operator: "LT",
    threshold: 2000,
    unit: "mg/day",
    ruleRole: "BENCHMARK",
    notes: ["Children require downward adjustment based on energy requirements; this adult threshold must not be copied unchanged into a child rule."],
  },
  {
    schemaVersion: 1,
    ruleId: "WHO_FRUIT_VEGETABLE_AGE_10_PLUS_MIN_400_G_DAY",
    sourceId: "WHO_HEALTHY_DIET_2026",
    sourceSection: "Healthy diet summary",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "AGE_10_PLUS",
    metric: "fruit_vegetable_g_day",
    operator: "GTE",
    threshold: 400,
    unit: "g/day",
    ruleRole: "BENCHMARK",
    notes: ["This is a population dietary benchmark, not a substitute for individualized clinical advice."],
  },
  {
    schemaVersion: 1,
    ruleId: "USDA_NOT_ANALYSED_DISTINCT_FROM_NOT_PRESENT",
    sourceId: "USDA_FDC_2026_04",
    sourceSection: "FoodData Central About Us; missing nutrient explanations",
    jurisdiction: "GLOBAL",
    evidenceClass: "AUTHORITATIVE_COMPOSITION",
    population: "DATA_SEMANTICS",
    metric: "nutrient_observation_state",
    operator: "SEMANTIC",
    threshold: null,
    unit: null,
    ruleRole: "DATA_SEMANTIC",
    notes: ["A component not yet analysed is not equivalent to a component known not to occur in a food."],
  },
  {
    schemaVersion: 1,
    ruleId: "FAO_INFOODS_FOOD_MATCHING_PRESERVES_CONTEXT",
    sourceId: "FAO_INFOODS_STANDARDS_2022",
    sourceSection: "FAO/INFOODS Guidelines for Food Matching",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    population: "DATA_SEMANTICS",
    metric: "food_match_quality",
    operator: "SEMANTIC",
    threshold: null,
    unit: null,
    ruleRole: "DATA_SEMANTIC",
    notes: ["Matching must consider food identity/form and source suitability; regional borrowing cannot silently become exact truth."],
  },
] as const;
