import { buildProvenance, type EvidenceSourceManifest } from "./contracts.ts";

const REVIEW_DATE = "2026-08-30";

type ManifestInput = Omit<EvidenceSourceManifest, "schemaVersion" | "provenance"> & {
  canonicalUri: string;
  licenseUri: string | null;
};

function manifest(input: ManifestInput): EvidenceSourceManifest {
  return {
    schemaVersion: 1,
    sourceId: input.sourceId,
    organization: input.organization,
    version: input.version,
    jurisdiction: input.jurisdiction,
    evidenceClass: input.evidenceClass,
    sourceRoles: input.sourceRoles,
    licenseStatus: input.licenseStatus,
    commercialUseStatus: input.commercialUseStatus,
    retentionRedistributionRules: input.retentionRedistributionRules,
    reviewDate: input.reviewDate,
    allowedUses: input.allowedUses,
    prohibitedUses: input.prohibitedUses,
    notes: input.notes,
    provenance: buildProvenance({
      sourceId: input.sourceId,
      organization: input.organization,
      version: input.version,
      canonicalUri: input.canonicalUri,
      licenseUri: input.licenseUri,
      reviewDate: input.reviewDate,
    }),
  };
}

export const EVIDENCE_SOURCE_MANIFESTS: readonly EvidenceSourceManifest[] = [
  manifest({
    sourceId: "USDA_FDC_2026_04",
    organization: "U.S. Department of Agriculture, Agricultural Research Service",
    version: "FoodData Central downloadable release 2026-04",
    jurisdiction: "US; global reference",
    evidenceClass: "AUTHORITATIVE_COMPOSITION",
    sourceRoles: ["PRODUCTION_NUTRITION_AUTHORITY"],
    licenseStatus: "PUBLIC_DOMAIN",
    commercialUseStatus: "ALLOWED",
    retentionRedistributionRules: [
      "FoodData Central states its data are public domain and published under CC0 1.0.",
      "Retain FDC identifier, data type, source version/date, nutrient identifier, unit, and derivation metadata for every imported value.",
      "Do not convert an unanalysed or absent field into a numeric zero.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://fdc.nal.usda.gov/download-datasets/",
    licenseUri: "https://fdc.nal.usda.gov/api-guide/",
    allowedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "BENCHMARK_VALIDATION", "REGIONAL_REFERENCE"],
    prohibitedUses: ["PACKAGED_LOOKUP"],
    notes: [
      "April 2026 is the latest downloadable release visible during the 2026-08-30 review.",
      "Foundation Foods is preferred when analytical provenance is important; branded records are label-derived and must retain their FDC data type.",
    ],
  }),
  manifest({
    sourceId: "OPEN_FOOD_FACTS_LIVE_2026_08_30",
    organization: "Open Food Facts",
    version: "Live database; evidence review 2026-08-30",
    jurisdiction: "GLOBAL",
    evidenceClass: "PACKAGED_PROVIDER",
    sourceRoles: ["PACKAGED_LOOKUP"],
    licenseStatus: "VERIFIED_OPEN",
    commercialUseStatus: "ALLOWED_WITH_OBLIGATIONS",
    retentionRedistributionRules: [
      "Database reuse is governed by ODbL with attribution and share-alike obligations.",
      "Keep Open Food Facts database-derived records license-isolated from authoritative composition datasets.",
      "This manifest covers database data only; product-image reuse requires a separately verified image/content licence before retention or redistribution.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://support.openfoodfacts.org/help/en-gb/12-api-data-reuse/94-are-there-conditions-to-use-the-api",
    licenseUri: "https://opendatacommons.org/licenses/odbl/1-0/",
    allowedUses: ["PACKAGED_LOOKUP", "BENCHMARK_VALIDATION", "ALIAS_REFERENCE"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP"],
    notes: [
      "Contributor-entered packaged-food data is reviewable against product labels but is not promoted to MoveFuel generic composition authority.",
      "A custom User-Agent and provider rate limits are part of API-use requirements.",
    ],
  }),
  manifest({
    sourceId: "NEPAL_DFTQC_PUBLICATIONS_2026_08_30",
    organization: "Department of Food Technology and Quality Control, Government of Nepal",
    version: "Publications reviewed 2026-08-30; reuse rights not cleared",
    jurisdiction: "NP",
    evidenceClass: "REGIONAL_REFERENCE",
    sourceRoles: ["REGIONAL_REFERENCE", "BENCHMARK_ONLY"],
    licenseStatus: "UNKNOWN",
    commercialUseStatus: "UNKNOWN",
    retentionRedistributionRules: [
      "Store bibliographic/provenance metadata only until reuse rights are explicitly cleared.",
      "Do not redistribute or ingest publication tables as production nutrient truth based solely on public web availability.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://dftqc.gov.np/",
    licenseUri: null,
    allowedUses: ["BENCHMARK_VALIDATION", "REGIONAL_REFERENCE", "ALIAS_REFERENCE"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP"],
    notes: ["DFTQC publishes analytical nutrition material, but no commercial reuse grant was verified during this review."],
  }),
  manifest({
    sourceId: "INDIA_IFCT_2017",
    organization: "ICMR-National Institute of Nutrition",
    version: "Indian Food Composition Tables 2017",
    jurisdiction: "IN",
    evidenceClass: "REGIONAL_REFERENCE",
    sourceRoles: ["REGIONAL_REFERENCE", "BENCHMARK_ONLY"],
    licenseStatus: "RIGHTS_GATED",
    commercialUseStatus: "REQUIRES_PERMISSION",
    retentionRedistributionRules: [
      "ICMR-NIN states that reproduction, distribution, transmission and automated scraping require prior written permission.",
      "Retain metadata/citations only; do not copy IFCT tables into production artifacts until permission is documented.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://www.nin.res.in/ebooks/IFCT2017.pdf",
    licenseUri: "https://www.nin.res.in/",
    allowedUses: ["BENCHMARK_VALIDATION", "REGIONAL_REFERENCE", "ALIAS_REFERENCE"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP"],
    notes: ["Benchmark/reference use must not reproduce protected table content."],
  }),
  manifest({
    sourceId: "BANGLADESH_FCT_2013",
    organization: "University of Dhaka Institute of Nutrition and Food Science / FAO",
    version: "Food Composition Table for Bangladesh, first edition 2013",
    jurisdiction: "BD",
    evidenceClass: "REGIONAL_REFERENCE",
    sourceRoles: ["REGIONAL_REFERENCE", "BENCHMARK_ONLY"],
    licenseStatus: "RIGHTS_GATED",
    commercialUseStatus: "UNKNOWN",
    retentionRedistributionRules: [
      "FAO lists the table as free access, but free access is not treated as a commercial redistribution licence.",
      "Retain bibliographic metadata only until commercial reuse and redistribution rights are explicitly verified.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://www.fao.org/food-composition/tables-and-databases/detail/%28country--date%29-title-1/en",
    licenseUri: null,
    allowedUses: ["BENCHMARK_VALIDATION", "REGIONAL_REFERENCE", "ALIAS_REFERENCE"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP"],
    notes: ["Rights-gated by MoveFuel policy pending an explicit reuse grant."],
  }),
  manifest({
    sourceId: "WHO_HEALTHY_DIET_2026",
    organization: "World Health Organization",
    version: "Healthy diet fact sheet updated 2026; linked WHO nutrient guidelines",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    sourceRoles: ["GUIDELINE_AUTHORITY"],
    licenseStatus: "RIGHTS_GATED",
    commercialUseStatus: "UNKNOWN",
    retentionRedistributionRules: [
      "Store concise derived rule facts and citations, not copied WHO publication text.",
      "Rules are benchmark constraints, not food-composition records.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
    licenseUri: null,
    allowedUses: ["GUIDELINE_RULE", "BENCHMARK_VALIDATION"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP"],
    notes: ["Specific rule artifacts preserve guideline scope and population caveats."],
  }),
  manifest({
    sourceId: "FAO_INFOODS_STANDARDS_2022",
    organization: "Food and Agriculture Organization of the United Nations / INFOODS",
    version: "Standards and guidelines page last updated 2022-10-20",
    jurisdiction: "GLOBAL",
    evidenceClass: "GUIDELINE",
    sourceRoles: ["GUIDELINE_AUTHORITY"],
    licenseStatus: "RIGHTS_GATED",
    commercialUseStatus: "UNKNOWN",
    retentionRedistributionRules: [
      "Store derived quality/matching rules and citations; do not assume publication copyright permits wholesale redistribution.",
      "Country/regional tables listed by INFOODS are evaluated independently; directory inclusion is not endorsement or a reuse licence.",
    ],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://www.fao.org/infoods/infoods/standards-guidelines/en/",
    licenseUri: null,
    allowedUses: ["GUIDELINE_RULE", "BENCHMARK_VALIDATION"],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP"],
    notes: ["Used for food matching, component semantics, quality and interchange benchmark rules."],
  }),
  manifest({
    sourceId: "UNKNOWN_LICENSE_FIXTURE",
    organization: "Unknown",
    version: "unknown",
    jurisdiction: "UNKNOWN",
    evidenceClass: "RESEARCH_EVIDENCE",
    sourceRoles: ["BENCHMARK_ONLY"],
    licenseStatus: "UNKNOWN",
    commercialUseStatus: "UNKNOWN",
    retentionRedistributionRules: ["Fail closed. Retain no substantive source content."],
    reviewDate: REVIEW_DATE,
    canonicalUri: "https://invalid.example/unknown-license-fixture",
    licenseUri: null,
    allowedUses: [],
    prohibitedUses: ["PRODUCTION_NUTRIENT_LOOKUP", "PACKAGED_LOOKUP", "REGIONAL_REFERENCE", "GUIDELINE_RULE", "ALIAS_REFERENCE"],
    notes: ["Synthetic policy fixture proving unknown licence never becomes authority."],
  }),
] as const;

export const EVIDENCE_SOURCE_BY_ID = new Map(EVIDENCE_SOURCE_MANIFESTS.map((source) => [source.sourceId, source]));
